In [1]:
import pandas as pd

In [ ]:
# load excerpt with only two vehicles to df

file_path = 'two_cars.csv'

# Create final DataFrame
columns = ['Track ID', 'Type', 'x [m]', 'y [m]', 'Speed [km/h]',
        'Tan. Acc. [ms-2]', 'Lat. Acc. [ms-2]', 'Time [s]', 'Angle [rad]']

df = pd.read_csv(file_path, delimiter=",")

df.head()

,Track ID,Type,x [m],y [m],Speed [km/h],Tan. Acc. [ms-2],Lat. Acc. [ms-2],Time [s],Angle [rad]
0,1,Car,411374.81,5655227.47,57.8746,-2.2080,-0.3367,0.066733,0.8582
1,1,Car,411375.17,5655227.89,57.6237,-1.9688,-0.3644,0.100100,0.8584
2,1,Car,411375.53,5655228.31,57.4030,-1.7065,-0.4042,0.133467,0.8586
3,1,Car,411375.89,5655228.73,57.2113,-1.4853,-0.4354,0.166833,0.8589
4,1,Car,411376.25,5655229.14,57.0482,-1.2287,-0.4692,0.200200,0.8592

## Conversion

The positional data in `two_cars.csv` is in the [UTM format](https://en.wikipedia.org/wiki/Universal_Transverse_Mercator_coordinate_system), specifically it refers to UTM zone 33, where `x`= Easting and `y`= Northing.
We need to convert it to x-y-positions in meter that are relative to the origin of the `xodr` map that we want to use, `map_hauptbahnhof_nord_dresden.osm`.

To do that, we use the `pyproj` package.

In [3]:
from pyproj import CRS, Transformer
from typing import Tuple


def convert_utm_to_local(
        easting: float, 
        northing: float,
        reference_lat: float=51.040659, 
        reference_lon: float=13.733844,
        utm_zone: int=33) -> Tuple[float, float]:
    """
    Converts UTM trajectory to local coordinates aligned with osm2xodr's tmerc projection.
    
    Parameters:
        df: pandas DataFrame with UTM columns
        utm_x_col: column name for UTM X (easting)
        utm_y_col: column name for UTM Y (northing)
        reference_lat: lat_0 from your .xodr geoReference (SW corner of OSM)
        reference_lon: lon_0 from your .xodr geoReference
        utm_zone: UTM zone of your trajectory (default: 33 for Dresden area)

    Returns:
        x_local, y_local
    """
    
    utm_crs = CRS.from_epsg(32600 + utm_zone) 
    tmerc_proj = f"+proj=tmerc +lat_0={reference_lat} +lon_0={reference_lon} +x_0=0 +y_0=0 +ellps=GRS80 +units=m +no_defs"
    local_crs = CRS.from_proj4(tmerc_proj)
    utm_to_local = Transformer.from_crs(utm_crs, local_crs, always_xy=True)

    x_local, y_local = utm_to_local.transform(easting, northing)

    return x_local, y_local

In [4]:
reference_lat, reference_lon = (51.0374498, 13.730641) # see `readme.md`

df[["x_loc [m]", "y_loc [m]"]] = df.apply(
    lambda row: pd.Series(
        convert_utm_to_local(
            row["x [m]"], 
            row["y [m]"], 
            reference_lat=reference_lat, 
            reference_lon=reference_lon
        )
    ), 
    axis=1
)

df.head()

,Track ID,Type,x [m],y [m],Speed [km/h],Tan. Acc. [ms-2],Lat. Acc. [ms-2],Time [s],Angle [rad],x_loc [m],y_loc [m]
0,1,Car,411374.81,5655227.47,57.8746,-2.2080,-0.3367,0.066733,0.8582,363.918235,477.886076
1,1,Car,411375.17,5655227.89,57.6237,-1.9688,-0.3644,0.100100,0.8584,364.271053,478.312345
2,1,Car,411375.53,5655228.31,57.4030,-1.7065,-0.4042,0.133467,0.8586,364.623871,478.738614
3,1,Car,411375.89,5655228.73,57.2113,-1.4853,-0.4354,0.166833,0.8589,364.976689,479.164883
4,1,Car,411376.25,5655229.14,57.0482,-1.2287,-0.4692,0.200200,0.8592,365.329679,479.581151

## Export the required fields for a single vehicle

In [5]:
# df[df["Track ID"] == 2].to_csv('2_vehicle_local_coords.csv', index=False, columns=["x_loc [m]", "y_loc [m]", "Time [s]"])

# Extract arbitrary trajectories from the full excerpt

In [ ]:
full_excerpt_path = "20220511_100012_Sid_StP_3W_d_1_1_ann.csv"
cols = "Track ID; Type; Track Width [m]; Track Width Displacement [m]; Track Length [m]; Track Length Displacement [m]; Entry Gate; Entry Time [s]; Exit Gate; Exit Time [s]; Traveled Dist. [m]; Avg. Speed [km/h]; Trajectory(x [m]; y [m]; Speed [km/h]; Tan. Acc. [ms-2]; Lat. Acc. [ms-2]; Time [s]; Angle [rad]; )" # this is the first line from the excerpt
cols = [c.strip() for c in cols.replace("(", "").replace(")", "").replace("Trajectory", "").strip().split(";")[:-1]]
trajectory_cols = cols[-7:] # these are the columns that designate the trajectory

In [7]:
trajectories = {}

with open(full_excerpt_path, "r") as f:

    #every line corresponds to one trajectory
    for line_number,line in enumerate(f):
        if line_number == 0:
            continue # skip the header
        print(f"line {line_number}, with {len(line.split(';'))} tokens")
        trajectory_id = line_number
        tokens = line.split(";")
        # we need to separate the trajectory from the trajectory metadata in tokens 0 to 11
        for token_number, token in enumerate(tokens):
            token = token.strip()
            if token_number == 0 or 1 < token_number < 12:
                continue
            elif token_number == 1:
                if token in ["Car", "Bus", "Medium Vehicle"]:
                    trajectories[trajectory_id] = {"type": token, "x": [], "y": [], "t": []}
                else: 
                    break # if trajectory does not belong to wanted class, break
            else: 
                trajectory_part = (token_number - 12) % 7
                try:
                    if trajectory_part == 0: # x [m]
                        trajectories[trajectory_id]["x"].append(float(token))
                    elif trajectory_part == 1: # y [m]
                        trajectories[trajectory_id]["y"].append(float(token))
                    elif trajectory_part == 5: # Time [s]
                        trajectories[trajectory_id]["t"].append(float(token))
                    else:
                        continue
                except Exception as e: 
                    print(f"Exception encountered at token {token_number}, trying to continue: {e}")

line 1, with 531 tokens
line 2, with 6635 tokens
line 3, with 1084 tokens
Exception encountered at token 1083, trying to continue: could not convert string to float: ''
line 4, with 769 tokens
Exception encountered at token 768, trying to continue: could not convert string to float: ''
line 5, with 1273 tokens
Exception encountered at token 1272, trying to continue: could not convert string to float: ''
line 6, with 6754 tokens
Exception encountered at token 6753, trying to continue: could not convert string to float: ''
line 7, with 447 tokens
Exception encountered at token 446, trying to continue: could not convert string to float: ''
line 8, with 15077 tokens
Exception encountered at token 15076, trying to continue: could not convert string to float: ''
line 9, with 67997 tokens
Exception encountered at token 67996, trying to continue: could not convert string to float: ''
line 10, with 2092 tokens
Exception encountered at token 2091, trying to continue: could not convert string to float: ''
line 11, with 2834 tokens
Exception encountered at token 2833, trying to continue: could not convert string to float: ''
line 12, with 11339 tokens
line 13, with 2764 tokens
Exception encountered at token 2763, trying to continue: could not convert string to float: ''
line 14, with 1756 tokens
line 15, with 2099 tokens
Exception encountered at token 2098, trying to continue: could not convert string to float: ''
line 16, with 2694 tokens
Exception encountered at token 2693, trying to continue: could not convert string to float: ''
line 17, with 2785 tokens
Exception encountered at token 2784, trying to continue: could not convert string to float: ''
line 18, with 2344 tokens
Exception encountered at token 2343, trying to continue: could not convert string to float: ''
line 19, with 2778 tokens
Exception encountered at token 2777, trying to continue: could not convert string to float: ''
line 20, with 1987 tokens
Exception encountered at token 1986, trying to continue: could not convert string to float: ''
line 21, with 12263 tokens
line 22, with 2757 tokens
Exception encountered at token 2756, trying to continue: could not convert string to float: ''
line 23, with 10919 tokens
line 24, with 25178 tokens
line 25, with 16554 tokens
line 26, with 2316 tokens
Exception encountered at token 2315, trying to continue: could not convert string to float: ''
line 27, with 2666 tokens
Exception encountered at token 2665, trying to continue: could not convert string to float: ''
line 28, with 1693 tokens
Exception encountered at token 1692, trying to continue: could not convert string to float: ''
line 29, with 3548 tokens
Exception encountered at token 3547, trying to continue: could not convert string to float: ''
line 30, with 9470 tokens
line 31, with 2407 tokens
Exception encountered at token 2406, trying to continue: could not convert string to float: ''
line 32, with 2680 tokens
Exception encountered at token 2679, trying to continue: could not convert string to float: ''
line 33, with 2519 tokens
Exception encountered at token 2518, trying to continue: could not convert string to float: ''
line 34, with 11010 tokens
line 35, with 2673 tokens
line 36, with 5004 tokens
line 37, with 6054 tokens
Exception encountered at token 6053, trying to continue: could not convert string to float: ''
line 38, with 5823 tokens
line 39, with 8287 tokens
line 40, with 16428 tokens
line 41, with 2260 tokens
Exception encountered at token 2259, trying to continue: could not convert string to float: ''
line 42, with 4787 tokens
Exception encountered at token 4786, trying to continue: could not convert string to float: ''
line 43, with 4108 tokens
Exception encountered at token 4107, trying to continue: could not convert string to float: ''
line 44, with 3387 tokens
line 45, with 13670 tokens
line 46, with 3100 tokens
Exception encountered at token 3099, trying to continue: could not convert string to float: ''
line 47, with 3779 tokens
Exception encountered at token 3778, trying to continue: could not convert string to float: ''
line 48, with 3226 tokens
Exception encountered at token 3225, trying to continue: could not convert string to float: ''
line 49, with 6439 tokens
line 50, with 3779 tokens
Exception encountered at token 3778, trying to continue: could not convert string to float: ''
line 51, with 42069 tokens
Exception encountered at token 42068, trying to continue: could not convert string to float: ''
line 52, with 10513 tokens
line 53, with 2155 tokens
Exception encountered at token 2154, trying to continue: could not convert string to float: ''
line 54, with 2393 tokens
Exception encountered at token 2392, trying to continue: could not convert string to float: ''
line 55, with 2358 tokens
Exception encountered at token 2357, trying to continue: could not convert string to float: ''
line 56, with 3296 tokens
line 57, with 2232 tokens
Exception encountered at token 2231, trying to continue: could not convert string to float: ''
line 58, with 2260 tokens
Exception encountered at token 2259, trying to continue: could not convert string to float: ''
line 59, with 2099 tokens
Exception encountered at token 2098, trying to continue: could not convert string to float: ''
line 60, with 2239 tokens
Exception encountered at token 2238, trying to continue: could not convert string to float: ''
line 61, with 2309 tokens
Exception encountered at token 2308, trying to continue: could not convert string to float: ''
line 62, with 5935 tokens
line 63, with 2526 tokens
Exception encountered at token 2525, trying to continue: could not convert string to float: ''
line 64, with 19396 tokens
line 65, with 9925 tokens
line 66, with 3779 tokens
line 67, with 2316 tokens
Exception encountered at token 2315, trying to continue: could not convert string to float: ''
line 68, with 13586 tokens
Exception encountered at token 13585, trying to continue: could not convert string to float: ''
line 69, with 2743 tokens
Exception encountered at token 2742, trying to continue: could not convert string to float: ''
line 70, with 2491 tokens
Exception encountered at token 2490, trying to continue: could not convert string to float: ''
line 71, with 37946 tokens
Exception encountered at token 37945, trying to continue: could not convert string to float: ''
line 72, with 2617 tokens
Exception encountered at token 2616, trying to continue: could not convert string to float: ''
line 73, with 2386 tokens
Exception encountered at token 2385, trying to continue: could not convert string to float: ''
line 74, with 15567 tokens
Exception encountered at token 15566, trying to continue: could not convert string to float: ''
line 75, with 3856 tokens
line 76, with 2120 tokens
Exception encountered at token 2119, trying to continue: could not convert string to float: ''
line 77, with 2302 tokens
Exception encountered at token 2301, trying to continue: could not convert string to float: ''
line 78, with 5739 tokens
line 79, with 2855 tokens
Exception encountered at token 2854, trying to continue: could not convert string to float: ''
line 80, with 2477 tokens
Exception encountered at token 2476, trying to continue: could not convert string to float: ''
line 81, with 2400 tokens
Exception encountered at token 2399, trying to continue: could not convert string to float: ''
line 82, with 2869 tokens
Exception encountered at token 2868, trying to continue: could not convert string to float: ''
line 83, with 2421 tokens
Exception encountered at token 2420, trying to continue: could not convert string to float: ''
line 84, with 2379 tokens
Exception encountered at token 2378, trying to continue: could not convert string to float: ''
line 85, with 2932 tokens
Exception encountered at token 2931, trying to continue: could not convert string to float: ''
line 86, with 41418 tokens
Exception encountered at token 41417, trying to continue: could not convert string to float: ''
line 87, with 2316 tokens
Exception encountered at token 2315, trying to continue: could not convert string to float: ''
line 88, with 2806 tokens
Exception encountered at token 2805, trying to continue: could not convert string to float: ''
line 89, with 2862 tokens
Exception encountered at token 2861, trying to continue: could not convert string to float: ''
line 90, with 2281 tokens
Exception encountered at token 2280, trying to continue: could not convert string to float: ''
line 91, with 2813 tokens
Exception encountered at token 2812, trying to continue: could not convert string to float: ''
line 92, with 40704 tokens
Exception encountered at token 40703, trying to continue: could not convert string to float: ''
line 93, with 2526 tokens
Exception encountered at token 2525, trying to continue: could not convert string to float: ''
line 94, with 2169 tokens
Exception encountered at token 2168, trying to continue: could not convert string to float: ''
line 95, with 6712 tokens
line 96, with 2484 tokens
Exception encountered at token 2483, trying to continue: could not convert string to float: ''
line 97, with 8196 tokens
line 98, with 2554 tokens
line 99, with 15392 tokens
line 100, with 5508 tokens
line 101, with 8539 tokens
line 102, with 9512 tokens
line 103, with 7727 tokens
line 104, with 12438 tokens
line 105, with 888 tokens
Exception encountered at token 887, trying to continue: could not convert string to float: ''
line 106, with 1735 tokens
Exception encountered at token 1734, trying to continue: could not convert string to float: ''
line 107, with 13250 tokens
line 108, with 7475 tokens
line 109, with 4703 tokens
Exception encountered at token 4702, trying to continue: could not convert string to float: ''
line 110, with 14965 tokens
line 111, with 16666 tokens
line 112, with 4899 tokens
Exception encountered at token 4898, trying to continue: could not convert string to float: ''
line 113, with 4780 tokens
line 114, with 8595 tokens
line 115, with 14020 tokens
line 116, with 12277 tokens
line 117, with 2057 tokens
Exception encountered at token 2056, trying to continue: could not convert string to float: ''
line 118, with 2939 tokens
Exception encountered at token 2938, trying to continue: could not convert string to float: ''
line 119, with 2491 tokens
Exception encountered at token 2490, trying to continue: could not convert string to float: ''
line 120, with 2092 tokens
Exception encountered at token 2091, trying to continue: could not convert string to float: ''
line 121, with 2337 tokens
Exception encountered at token 2336, trying to continue: could not convert string to float: ''
line 122, with 10674 tokens
line 123, with 18472 tokens
line 124, with 2624 tokens
Exception encountered at token 2623, trying to continue: could not convert string to float: ''
line 125, with 5235 tokens
line 126, with 2701 tokens
Exception encountered at token 2700, trying to continue: could not convert string to float: ''
line 127, with 9330 tokens
line 128, with 2582 tokens
Exception encountered at token 2581, trying to continue: could not convert string to float: ''
line 129, with 482 tokens
Exception encountered at token 481, trying to continue: could not convert string to float: ''
line 130, with 6677 tokens
line 131, with 2505 tokens
Exception encountered at token 2504, trying to continue: could not convert string to float: ''
line 132, with 2659 tokens
Exception encountered at token 2658, trying to continue: could not convert string to float: ''
line 133, with 2981 tokens
line 134, with 8056 tokens
line 135, with 10751 tokens
line 136, with 2715 tokens
Exception encountered at token 2714, trying to continue: could not convert string to float: ''
line 137, with 2204 tokens
Exception encountered at token 2203, trying to continue: could not convert string to float: ''
line 138, with 2428 tokens
Exception encountered at token 2427, trying to continue: could not convert string to float: ''
line 139, with 3352 tokens
line 140, with 2659 tokens
Exception encountered at token 2658, trying to continue: could not convert string to float: ''
line 141, with 7699 tokens
line 142, with 3380 tokens
Exception encountered at token 3379, trying to continue: could not convert string to float: ''
line 143, with 2799 tokens
Exception encountered at token 2798, trying to continue: could not convert string to float: ''
line 144, with 2302 tokens
Exception encountered at token 2301, trying to continue: could not convert string to float: ''
line 145, with 2491 tokens
Exception encountered at token 2490, trying to continue: could not convert string to float: ''
line 146, with 7692 tokens
line 147, with 2547 tokens
Exception encountered at token 2546, trying to continue: could not convert string to float: ''
line 148, with 16897 tokens
Exception encountered at token 16896, trying to continue: could not convert string to float: ''
line 149, with 2344 tokens
Exception encountered at token 2343, trying to continue: could not convert string to float: ''
line 150, with 2407 tokens
Exception encountered at token 2406, trying to continue: could not convert string to float: ''
line 151, with 5137 tokens
line 152, with 2743 tokens
Exception encountered at token 2742, trying to continue: could not convert string to float: ''
line 153, with 4108 tokens
line 154, with 2918 tokens
Exception encountered at token 2917, trying to continue: could not convert string to float: ''
line 155, with 2890 tokens
Exception encountered at token 2889, trying to continue: could not convert string to float: ''
line 156, with 2204 tokens
Exception encountered at token 2203, trying to continue: could not convert string to float: ''
line 157, with 2414 tokens
Exception encountered at token 2413, trying to continue: could not convert string to float: ''
line 158, with 17555 tokens
line 159, with 3254 tokens
Exception encountered at token 3253, trying to continue: could not convert string to float: ''
line 160, with 2393 tokens
Exception encountered at token 2392, trying to continue: could not convert string to float: ''
line 161, with 4535 tokens
Exception encountered at token 4534, trying to continue: could not convert string to float: ''
line 162, with 6229 tokens
line 163, with 7111 tokens
line 164, with 3219 tokens
Exception encountered at token 3218, trying to continue: could not convert string to float: ''
line 165, with 4346 tokens
Exception encountered at token 4345, trying to continue: could not convert string to float: ''
line 166, with 2323 tokens
Exception encountered at token 2322, trying to continue: could not convert string to float: ''
line 167, with 14202 tokens
Exception encountered at token 14201, trying to continue: could not convert string to float: ''
line 168, with 2295 tokens
Exception encountered at token 2294, trying to continue: could not convert string to float: ''
line 169, with 8371 tokens
line 170, with 14699 tokens
Exception encountered at token 14698, trying to continue: could not convert string to float: ''
line 171, with 5515 tokens
line 172, with 14048 tokens
Exception encountered at token 14047, trying to continue: could not convert string to float: ''
line 173, with 5417 tokens
line 174, with 8028 tokens
line 175, with 11640 tokens
line 176, with 11654 tokens
line 177, with 5333 tokens
Exception encountered at token 5332, trying to continue: could not convert string to float: ''
line 178, with 8441 tokens
line 179, with 6201 tokens
line 180, with 2792 tokens
line 181, with 4213 tokens
Exception encountered at token 4212, trying to continue: could not convert string to float: ''
line 182, with 2246 tokens
Exception encountered at token 2245, trying to continue: could not convert string to float: ''
line 183, with 5466 tokens
line 184, with 4290 tokens
line 185, with 664 tokens
Exception encountered at token 663, trying to continue: could not convert string to float: ''

In [8]:
# Check whether for every trajectory id, the x, y and t lists have the same length

for trajectory_id in trajectories:
    len_x = len(trajectories[trajectory_id]["x"])
    len_y = len(trajectories[trajectory_id]["y"])
    len_t = len(trajectories[trajectory_id]["t"])
    if len_x != len_y or len_x != len_t or len_y != len_t:
        print(f"Mismatch at {trajectory_id}")

## Convert trajectory coordinates from UTM to local

In [9]:
# reference_lat, reference_lon = (51.0374498, 13.730641) # see `readme.md`

# for trajectory_id in trajectories:
#     xs = trajectories[trajectory_id]["x"]
#     ys = trajectories[trajectory_id]["y"]
#     ts = trajectories[trajectory_id]["t"]

#     trajectories[trajectory_id]["local_coords"] = []

#     print(f"Processing trajectory {trajectory_id}")

#     for i in range(len(xs)):
#         x_local, y_local = convert_utm_to_local(xs[i], ys[i], reference_lat, reference_lon)
#         trajectories[trajectory_id]["local_coords"].append((x_local, y_local, ts[i]))

In [10]:
# make a fat parallelized conversion to local coordinates

from concurrent.futures import ProcessPoolExecutor, as_completed

reference_lat, reference_lon = (51.0374498, 13.730641)  # see `readme.md`

def process_trajectory(traj_id_and_data):
    trajectory_id, data = traj_id_and_data
    xs, ys, ts = data["x"], data["y"], data["t"]
    
    local_coords = [
        (*convert_utm_to_local(xs[i], ys[i], reference_lat, reference_lon), ts[i])
        for i in range(len(xs))
    ]
    
    return trajectory_id, local_coords


with ProcessPoolExecutor() as executor:
    futures = [executor.submit(process_trajectory, (tid, trajectories[tid])) for tid in trajectories]

    completed_count = 0
    for future in as_completed(futures):
        trajectory_id, local_coords = future.result()
        completed_count += 1
        print(f"Processed {completed_count} trajectories")
        trajectories[trajectory_id]["local_coords"] = local_coords

Processed 1 trajectories
Processed 2 trajectories
Processed 3 trajectories
Processed 4 trajectories
Processed 5 trajectories
Processed 6 trajectories
Processed 7 trajectories
Processed 8 trajectories
Processed 9 trajectories
Processed 10 trajectories
Processed 11 trajectories
Processed 12 trajectories
Processed 13 trajectories
Processed 14 trajectories
Processed 15 trajectories
Processed 16 trajectories
Processed 17 trajectories
Processed 18 trajectories
Processed 19 trajectories
Processed 20 trajectories
Processed 21 trajectories
Processed 22 trajectories
Processed 23 trajectories
Processed 24 trajectories
Processed 25 trajectories
Processed 26 trajectories
Processed 27 trajectories
Processed 28 trajectories
Processed 29 trajectories
Processed 30 trajectories
Processed 31 trajectories
Processed 32 trajectories
Processed 33 trajectories
Processed 34 trajectories
Processed 35 trajectories
Processed 36 trajectories
Processed 37 trajectories
Processed 38 trajectories
Processed 39 trajectories
Processed 40 trajectories
Processed 41 trajectories
Processed 42 trajectories
Processed 43 trajectories
Processed 44 trajectories
Processed 45 trajectories
Processed 46 trajectories
Processed 47 trajectories
Processed 48 trajectories
Processed 49 trajectories
Processed 50 trajectories
Processed 51 trajectories
Processed 52 trajectories
Processed 53 trajectories
Processed 54 trajectories
Processed 55 trajectories
Processed 56 trajectories
Processed 57 trajectories
Processed 58 trajectories
Processed 59 trajectories
Processed 60 trajectories
Processed 61 trajectories
Processed 62 trajectories
Processed 63 trajectories
Processed 64 trajectories
Processed 65 trajectories
Processed 66 trajectories
Processed 67 trajectories
Processed 68 trajectories
Processed 69 trajectories
Processed 70 trajectories
Processed 71 trajectories
Processed 72 trajectories
Processed 73 trajectories
Processed 74 trajectories
Processed 75 trajectories
Processed 76 trajectories
Processed 77 trajectories
Processed 78 trajectories
Processed 79 trajectories
Processed 80 trajectories
Processed 81 trajectories
Processed 82 trajectories
Processed 83 trajectories
Processed 84 trajectories
Processed 85 trajectories
Processed 86 trajectories
Processed 87 trajectories
Processed 88 trajectories
Processed 89 trajectories
Processed 90 trajectories
Processed 91 trajectories
Processed 92 trajectories
Processed 93 trajectories
Processed 94 trajectories
Processed 95 trajectories
Processed 96 trajectories
Processed 97 trajectories
Processed 98 trajectories
Processed 99 trajectories
Processed 100 trajectories
Processed 101 trajectories
Processed 102 trajectories
Processed 103 trajectories
Processed 104 trajectories
Processed 105 trajectories
Processed 106 trajectories
Processed 107 trajectories
Processed 108 trajectories
Processed 109 trajectories
Processed 110 trajectories
Processed 111 trajectories
Processed 112 trajectories
Processed 113 trajectories
Processed 114 trajectories
Processed 115 trajectories

In [16]:
# Export

for trajectory_id, trajectory_data in trajectories.items():
    vehicle_type = trajectory_data["type"]
    local_coords = trajectory_data["local_coords"]
    with open(f"{trajectory_id}_{vehicle_type}_local_coords.csv", "w") as openf:
        print("x_loc [m],y_loc [m],Time [s]", file=openf)

        for x,y,t in local_coords:
            print(x, y, t, sep=",", file=openf)